name: BlockFreezer
main: blockfreezer\BlockFreezer
version: 1.4.0
api: [1.10.0, 2.0.0]
load: POSTWORLD
author: Gamecrafter
description: Control what blocks update in your worlds!
website: https://github.com/Viperize/BlockFreezer-PocketMine
permissions:
 blockfreezer:
  default: op
  children:
   blockfreezer.command:
    default: op
    children:
     blockfreezer.command.blockfreezer:
      default: op